In [1]:
import sys
import numpy as np

sys.path.append("library");


In [2]:
import FeatureSelection.Metrics.FeatureInformation as FI

InfA=FI.InformationAnalysis([1,2,3,3,4],[-1,-1,-1,-1,2],2,2)
print(InfA.MutualInformation())
print(InfA.JointEntropy())
print(InfA.EntropyA())
print(InfA.EntropyB())

print(InfA.Pab)
InfB=FI.InformationAnalysis(InfA.Pab)
print(InfB.MutualInformation())
print(InfB.JointEntropy())
print(InfB.EntropyA())
print(InfB.EntropyB())

0.17095059445466854
1.5219280948873621
0.9709505944546686
0.7219280948873623
[[0.4 0. ]
 [0.4 0.2]]
0.17095059445466845
1.5219280948873621
0.9709505944546686
0.7219280948873623


In [4]:
import DensityEstimation.KdeExtras as kext
from sklearn.neighbors import KernelDensity

XX=[[1,2],[2,3],[-1,2],[2,1],[3,3],[2,3]];
kde = KernelDensity(kernel='gaussian', bandwidth=0.5).fit(XX)
P=kext.kde_get2d_joint_prob(kde, -1,3,3,1,3,3)

print(P)

[[0.02942515 0.21742407 0.02942516]
 [0.05886019 0.22937672 0.08833849]
 [0.0295178  0.04143097 0.27620146]]
